### PR TITLE
Fix IndexOutOfBoundsException

### PR DESCRIPTION
**Pull request by virengujariya**
Prevent `IndexOutOfBoundsException`

### CODE REVIEW

**Comment by virengujariya** [comment]
@hendraanggrian @stasbar Can you please review this?

**Comment by hendraanggrian** [comment]
Hi there, my apologies for slow response. I'm currently out of town and didn't bring my computer with me to test this. I will be back tomorrow, and will certainly review this as I welcome any kind of contribution. Sorry again!

**Comment by hendraanggrian** [comment]
Hi @virengujariya, are you sure `text.length() - 1` is necessary?

Here is a source code of [SpannedStringKt of androidx-core](https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/core/ktx/src/main/java/androidx/core/text/SpannedString.kt). In there, the end parameter is `SpannedString`'s length without `- 1`.

**Comment by virengujariya** [comment]
@hendraanggrian Finally I am able to reproduce this issue,
Reproduction steps (On device Samsung Galaxy S8)
- type text `This is a test that will break @one @two @xyz blah blah blah`
- select `blah blah blah` and cut (using android pop-over cut, select all) 

Let me know if you need more details. I am not sure if there is anything we can do to it fix on our end. Maybe we can try handling `IndexOutOfBoundsException`

**Comment by virengujariya** [comment]
@hendraanggrian @stasbar Refer fix from another repo https://github.com/stefan-niedermann/nextcloud-notes/blob/c20e49d50a33d4c86bb5d46717bb5666f2213c59/app/src/main/java/it/niedermann/owncloud/notes/util/DisplayUtils.java

**Comment by hendraanggrian** [comment]
I assume this is related to #68.

**Pull request closed without merging**
